version: "3"
services:

  django:
    build:
      context: backend
    command:
      - sh
      - -c
      - |
        cd backend
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  react:
    build:
      context: frontend
    command:
      - sh
      - -c
      - |
        cd frontend
        npm start
    volumes:
      - .:/app
    depends_on:
      - django
    ports:
      - "3000:3000"