# Generated by Django 4.2.4 on 2023-08-18 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=256)),
            ],
        ),
    ]
