# Generated by Django 4.2.4 on 2023-08-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helm_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='People',
        ),
    ]
