# Generated by Django 4.2.4 on 2023-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm_app_backend', '0002_rename_entry_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
