apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  labels:
    app: backend

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend-deployment
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-backend-secrets

          command: ["sh", "-c"]
          args:
            - |
              python manage.py migrate
              python manage.py runserver 0.0.0.0:{{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  selector:
    app: {{ .Release.Name }}-backend-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}