apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend

spec:
  selector:
    matchLabels:
      app: frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend
          image: lukaross123/helm-app:frontend-1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000